#+TITLE:     Bli medlem i Fripost
#+SETUPFILE: includes/level-0.org

För att gå med i Fripost, betala medlemsavgiften och skicka ett mail med din
information enligt nedan.  Din information kan du skicka till Stefan Kangas på
[[mailto:skangas@skangas.se][skangas@skangas.se]] (om du vill kan du kryptera informationen till PGP-nyckel
0xXXXXXXXX).

#+HTML: <div class="divider"></div>

** Medlemskapet

Som medlem får man:

- En e-postadress, en inkorg och möjlighet till ett extra alias på fripost.org
- Möjlighet att associera en av dina egna domäner till våra e-postservrar
- Ett obegränsat antal alias på din egen domän

#+HTML: <div class="divider"></div>

** Betalning

Det enklaste sättet att betala *medlemsavgiften på 300 kronor* är genom:

|----------+----------|
| Plusgiro | 477884-1 |
| Bankgiro | 311-5060 |
|----------+----------|

#+HTML: <br /><!-- FIXME: fulhack -->

Lämna ditt namn eller önskade användarnamn i meddelandefältet. Det är också
möjligt att betala kontant på någon av föreningens träffar.

#+HTML: <div class="divider"></div>

** Medlemsinformation

Fripost bryr sig i medlemmarnas integritet och uppmuntrar till försiktighet när
det gäller att lämna ut personuppgifter.  I den andan erbjuder Fripost anonymt
medlemskap, för vilka det enda vi behöver veta är:

- Den önskade e-postadressen (dittnamn@fripost.org)

För att möjliggöra för Fripost att nå dig med viktig information kan du också
lämna:

- Ditt hela namn
- Nuvarande e-postadress (rekommenderat)
- Telefon- och mobilnummer
- Fysisk adress
- Om du vill gå med i e-postlistan

E-postlistan för medlemmar är den huvudsakliga informationskanalen inom
föreningen.  Medlemmar läggs inte till automatiskt, utan du måste uttryckligen
säga till att du vill gå med.

#+HTML: <div class="divider"></div>

** Krav för medlemskap 

Det enda kravet för att bli medlem är att man måste bo i Sverige. Notera att det
inte finns några som helst krav på att man ska vara svensk medborgare, det enda
kravet är att du bor här.

#+HTML: <div class="divider"></div>

** Övrigt

För att få igång vår e-posttjänst ordentligt måste vi nå ett tillräckligt antal
medlemmar.  Lägsta beloppet vi behöver är runt 15 000 kronor. Med en
medlemsavgift på 300 kronor behöver vi alltså 50 medlemmar innan vi kan komma
igång på allvar.  Med din hjälp är det inga problem.

