#+TITLE:     Vanliga frågor om Fripost
#+SETUPFILE: includes/level-0.org
#+OPTIONS:   toc:t num:t

#+HTML: <div class="divider"></div>

** Allmänt om Föreningen

*** Vad är fria e-postföreningen?

Vi är en grupp som organiserat oss för att försvara våra intressen i en
alltmer digitaliserad värld. Detta genom att sätta igång en autonom och tekniskt
riktig infrastruktur för e-post.

Vi vill ta tillbaka makten över vår information och vårt privatliv.

*** När bildades föreningen?

Föreningen bildades formellt den 4 november 2010, men redan innan dess pågick
förberedelser, diskussion och planering.  Idén att starta föreningen väcktes
redan i april samma år.

*** Var är föreningens säte?

Föreningen har sitt säte i Göteborg.

*** Vem kan gå med?

Det enda kravet för medlemskap är att man bor i Sverige.

Meningen med begränsningen är att det måste vara möjligt för medlemmar,
åtminstone i teorin, att delta på ett årsmöte.  Det är väldigt svårt att delta i
föreningen om man bor i ett helt annat land.  Om någon från Italien vill gå med
är det till större nytta om hon startar en egen förening för alla italienare.

#+HTML: <div class="divider"></div>

** Vårt arbete

*** Hur långt har ni kommit?

Våra system används varje dag av Friposts medlemmar. Vår webmail finns [[https://mail.fripost.org/][här]], och
den som är nyfiken kan hitta skärmdumpar [[http://roundcube.net/screens][här]].

Vi satsar just nu på att rekrytera fler medlemmar för att skapa ekonomiska
möjligheter att öka systemets stabilitet och tillförlitlighet. Vårt mål för
första året är 50 medlemmar. På sidan [[file:medlemskap.org][bli medlem]] finns en räknare över antalet
medlemmar.

# << dyrt >>

*** Varför är det så dyrt att gå med?

Medlemsavgiften är bestämd av årsmötet till 300 kronor per år.

Fripost använder för närvarande uteslutande hårdvara och internetuppkoppling som
solidariska medlemmar donerat eller lånat ut. Det kommer vi fortsätta göra. Men
för att kunna bygga en bra lösning för e-post måste vissa grejer köpas in som
helt enkelt är för dyra för att någon enskild ska kunna donera dem. Innan vi
gjort dessa inköp kan vi inte nå den tillförlitlighet som är nödvändig för
någonting så viktigt som e-post. De största utgiftsposterna är lagringsutrymme
till våra e-brev och säkerhetskopior samt kostnad för riktigt bra hostning för
en huvudserver.

Hur mycket det kommer att kosta att vara med i framtiden vet vi inte.  Det beror
bland annat på hur många vi lyckas rekrytera: det borde vara lättare att sänka
medlemsavgiften om vi är fler som delar på kostnaderna. Ett sådant beslut fattas
på föreningens årsmöte dit du som medlem är välkommen att komma och göra din
röst hörd.

Det är inte heller gratis att stå utanför Fripost. Företag och stater kartlägger
din kommunikation, sparar informationen kanske för alltid och utnyttjar den till
riktad marknadsföring idag och vem vet vad imorgon. Detta är vad deras så
kalllade gratistjänster erbjuder.

Sett i det perspektivet tycker vi att 300 kronor är ett lågt pris för frihet.

#+HTML: <div class="divider"></div>

** Skillnaden mellan oss och andra

*** Hur skiljer ni er från andra e-postleverantörer?

Vi är ingen e-postleverantör!  Vi är en förening som förvisso råkar
tillhandahålla just e-posttjänster till sina medlemmar, men det är fel att tänka
på medlemsskapet som ett kundförhållande. Rätt är att se det som att den som är
medlem har bestämt sig för att organiserat och tillsammans med andra ta kontroll
över (en del av) sin kommunikation.

Vi jämför oss hellre med facket eller Hyresgästföreningen än med
Bredbandsbolaget eller Bahnhof.

Om du ändå vill ha en lista, här är den:

- Inget vinstintresse.  Alla pengar vi får in går till föreningens verksamhet,
  som är att hålla igång e-posttjänster och informationsspridning.

- Genomskinlighet.  Allt som sker beslutas demokratiskt och öppet.

- Medlemmarna har makten.  På föreningens årsmöten formar vi föreningen
  gemensamt, fattar viktiga beslut och stakar ut den riktning vi ska gå i
  framtiden.

*** Jag har hört om företaget X, Y eller Z som säljer "integritetssäkrad" e-post.  Kan jag inte bara köpa deras tjänst?

Så klart /kan/ du köpa en tjänst av ett privat företag.  Frågan är varför du skulle vilja det.

När du köper en tjänst av ett företag hamnar du i en väldigt speciell relation
till dem: du blir deras kund.  Som kund har du svårt att påverka annat än genom
att gå därifrån.  I bästa fall har deras användaravtal (som du kanske godkände
för att få bli kund) bestämmelser som ger dig kontrollen över din data.  Om du
lämnar företaget har du emellertid sällan några garantier för att inte din
information ligger och skräpar på deras servrar.  Företaget har inte något
direkt intresse av att ta bort den.

Som kund hos ett privat företag har du ingen egentlig makt över företaget.  Det
är alltid företagets ägare som har sista ordet.

Hos Fripost blir du medlem på lika villkor som alla andra.  Du har rätt att
delta på föreningens årsmöten och där tala för din sak.  Tillsammans med andra
kan du rösta bort eller rösta fram en viss ledning.  Eller avskaffa ledningen.
Poängen är att du blir medlem och i Fripost är det medlemmarna som bestämmer.

Frågan är också denna: Ett företag är en juridisk person som på ett eller annat
sätt vill tjäna pengar på dig.  Fripost är en förening av likasinnade, av
kamrater som brinner för integritetsfrågor.  Vem litar du mest på?

#+HTML: <div class="divider"></div>

** Våra mål

*** Strävar ni efter världsdominans?

Nej. Vi hoppas att folk kopierar vårt koncept och bygger demokratiskt
kontrollerad infrastruktur för e-post och allt annat. Helst skulle vi se att det
fanns en Folkets tekniska infrastrukturkommitté i varje kvarter, men än så
länge...

