#+TITLE:     Bli medlem i Fripost
#+SETUPFILE: includes/level-0.org

#+BEGIN_HTML
	<!-- jsProgressBarHandler prerequisites : prototype.js -->
	<script type="text/javascript" src="js/prototype/prototype.js"></script>

	<!-- jsProgressBarHandler core -->
	<script type="text/javascript" src="js/bramus/jsProgressBarHandler.js"></script>

<div class="square">
<h1>Medlemsräknare</h1>

<p>16 av 50 medlemmar<br />
<span class="progressBar" id="element1">32%</span></p>

<p>För att komma igång ordentligt måste vi få ihop 15&nbsp;000 kronor, alltså 50
medlemmar. Här räknar vi bara folk som har betalat medlemsavgiften. Det är många
som har sagt att de absolut ska gå med, men väntar på nästa löning eller
liknande. Är du en av dem? Dags att gå till handling! :-)
</p>
</div>
#+END_HTML

För att gå med i Fripost, betala medlemsavgiften (300 kronor) och skicka ett
mail med din information enligt nedan.  Din information kan du skicka till
Stefan Kangas på [[mailto:skangas@skangas.se][skangas@skangas.se]].

Om du vill och vet hur man gör så kan du kryptera din information till
PGP-nyckel 0x8F4353EE.

** Medlemskapet

Som medlem får man:

- En e-postadress, en inkorg och möjlighet till ett extra alias på fripost.org
- Möjlighet att koppla en av dina egna domäner till våra e-postservrar
- Ett obegränsat antal alias på din egen domän

#+HTML: <div class="divider"></div>

** Betalning

Det enklaste sättet att betala *medlemsavgiften på 300 kronor* är genom:

|----------+----------|
| Plusgiro | 477884-1 |
| Bankgiro | 311-5060 |
|----------+----------|

#+HTML: <br /><!-- FIXME: fulhack -->

Lämna ditt namn eller önskade användarnamn i meddelandefältet. Det är också
möjligt att betala kontant på någon av föreningens träffar.

#+HTML: <div class="divider"></div>

** Medlemsinformation

Fripost bryr sig om medlemmarnas integritet och uppmuntrar till försiktighet vad
gäller att lämna ut personuppgifter.  I den andan erbjuder Fripost anonymt
medlemskap, för vilket det enda vi behöver veta är:

- Den önskade e-postadressen (dittnamn@fripost.org)

För att möjliggöra för Fripost att nå dig med viktig information kan du också
välja att lämna:

- Ditt riktiga namn
- Nuvarande e-postadress (rekommenderat)
- Telefon- och mobilnummer
- Fysisk adress
- Om du vill gå med i e-postlistan

E-postlistan för medlemmar är den huvudsakliga informationskanalen inom
föreningen.  Medlemmar läggs inte till automatiskt, utan du måste uttryckligen
säga till att du vill gå med.

#+HTML: <div class="divider"></div>

** Krav för medlemskap 

Det enda kravet för att bli medlem är att man måste bo i Sverige. Notera att det
inte finns några som helst krav på att man ska vara svensk medborgare, det enda
kravet är att du bor här.

#+HTML: <div class="divider"></div>

# << ovrigt >>
** Övrigt

För att få igång vår e-posttjänst ordentligt måste vi nå ett tillräckligt antal
medlemmar.  Lägsta beloppet vi behöver är runt 15 000 kronor. Med en
medlemsavgift på 300 kronor behöver vi alltså 50 medlemmar innan vi kan komma
igång på allvar.  Med din hjälp är det inga problem. [[file:faq.html#dyrt][Läs mer här!]]
