#+TITLE:     Bli medlem i Fripost
#+SETUPFILE: includes/level-0.org

#+BEGIN_HTML
	<!-- jsProgressBarHandler prerequisites : prototype.js -->
	<script type="text/javascript" src="js/prototype/prototype.js"></script>

	<!-- jsProgressBarHandler core -->
	<script type="text/javascript" src="js/bramus/jsProgressBarHandler.js"></script>

<div class="square">
<h1>Medlemsräknare</h1>

<p>42 av 50 medlemmar<br />
<span class="progressBar" id="element1">84 %</span></p>

<p>Vårt mål för första året är att få ihop 50 medlemmar, då medlemsavgifterna
ger en ekonomisk lägsta nivå för att säkra föreningens stabilitet. Här räknar vi
bara folk som har betalat medlemsavgiften. Det är många som har sagt att de
absolut ska gå med, men väntar på nästa löning eller liknande. Är du en av dem?
Dags att gå till handling! :-) </p> </div>
#+END_HTML

För att gå med i Fripost, betala medlemsavgiften (300 kronor per år) enligt nedan.

|----------+----------|
| Plusgiro | 477884-1 |
| Bankgiro | 311-5060 |
|----------+----------|

#+HTML: <br /><!-- FIXME: fulhack -->

Glöm inte att lämna kontaktuppgifter i meddelandefältet så vi kan nå dig. En
e-postadress och/eller ett telefonnummer är fullt tillräckligt.

Det går naturligtvis också att betala kontant på någon av [[http://wiki.fripost.org/moten/][föreningens träffar]].

** Vad innebär medlemskapet?

Att bli medlem i vår förening betyder att man träder in på samma villkor som
alla andra. Det betyder alltså inte bara att man får en e-post fri från
övervakning, utan man blir samtidigt en del av något större.

I Fripost är alla så aktiva eller inaktiva som de vill, men varje medlem har
samma rätt och möjlighet att delta i föreningens interna demokratiska liv.

Som medlem får man dessutom:

- En e-postadress, en inkorg och möjlighet till ett extra alias på fripost.org
- Möjlighet att koppla en av dina egna domäner till våra e-postservrar
- Ett obegränsat antal alias på din egen domän

Om du har några frågor om medlemskapet eller något annat, tveka inte att [[file:kontakt.org][kontakta oss]].

#+HTML: <div class="divider"></div>

** Anonymt medlemskap

Fripost bryr sig om medlemmarnas integritet och uppmuntrar till försiktighet med
att lämna ut personuppgifter. I den andan erbjuder Fripost anonymt medlemskap,
för vilket det enda vi behöver veta är vilken e-postadress du vill ha och ett
sätt att nå dig.

#+HTML: <div class="divider"></div>

** Krav för medlemskap 

Det enda kravet för att bli medlem är att man måste bo i Sverige. Notera att det
inte finns några som helst krav på att man ska vara svensk medborgare, det enda
kravet är att du bor här.
