#+TITLE:     Bli medlem i Fripost
#+SETUPFILE: includes/level-0.org

#+BEGIN_HTML
	<!-- jsProgressBarHandler prerequisites : prototype.js -->
	<script type="text/javascript" src="js/prototype/prototype.js"></script>

	<!-- jsProgressBarHandler core -->
	<script type="text/javascript" src="js/bramus/jsProgressBarHandler.js"></script>

<div class="square">
<h1>Medlemsräknare</h1>

<p>36 av 50 medlemmar<br />
<span class="progressBar" id="element1">72%</span></p>

<p>Vårt mål för första året är att få ihop 50 medlemmar, då medlemsavgifterna
ger en ekonomisk lägsta nivå för att säkra föreningens stabilitet. Här räknar vi
bara folk som har betalat medlemsavgiften. Det är många som har sagt att de
absolut ska gå med, men väntar på nästa löning eller liknande. Är du en av dem?
Dags att gå till handling! :-) </p> </div>
#+END_HTML

För att gå med i Fripost, betala medlemsavgiften (300 kronor per år) och skicka
ett mail med din information enligt nedan.  Din information kan du skicka till
Stefan Kangas på [[mailto:skangas@skangas.se][skangas@skangas.se]].

Om du vill och vet hur man gör så kan du kryptera din information till
PGP-nyckel 0x8F4353EE.

** Medlemskapet

Som medlem får man:

- En e-postadress, en inkorg och möjlighet till ett extra alias på fripost.org
- Möjlighet att koppla en av dina egna domäner till våra e-postservrar
- Ett obegränsat antal alias på din egen domän

#+HTML: <div class="divider"></div>

** Betalning

Det enklaste sättet att betala *medlemsavgiften på 300 kronor* är genom:

|----------+----------|
| Plusgiro | 477884-1 |
| Bankgiro | 311-5060 |
|----------+----------|

#+HTML: <br /><!-- FIXME: fulhack -->

Lämna ditt namn eller önskade användarnamn i meddelandefältet.

Det är också möjligt att betala kontant på någon av [[http://wiki.fripost.org/moten/][föreningens träffar]].

#+HTML: <div class="divider"></div>

** Medlemsinformation

Fripost bryr sig om medlemmarnas integritet och uppmuntrar till försiktighet vad
gäller att lämna ut personuppgifter.  I den andan erbjuder Fripost anonymt
medlemskap, för vilket det enda vi behöver veta är:

- Den önskade e-postadressen (dittnamn@fripost.org)

För att möjliggöra för Fripost att nå dig med viktig information kan du också
välja att lämna:

- Ditt riktiga namn
- Nuvarande e-postadress (rekommenderat)
- Telefon- och mobilnummer
- Fysisk adress
- Om du vill gå med i e-postlistan

#+HTML: <div class="divider"></div>

** Krav för medlemskap 

Det enda kravet för att bli medlem är att man måste bo i Sverige. Notera att det
inte finns några som helst krav på att man ska vara svensk medborgare, det enda
kravet är att du bor här.
