#+TITLE:     Föreningen Fripost
#+SETUPFILE: includes/level-0.org

#+BEGIN_HTML
<div class="square">
<h1>Logga in</h1>
<p>Du som är medlem kan logga in på din e-post <a href="https://mail.fripost.org/">här</a>.
</p>
</div>
#+END_HTML

Fripost är en demokratisk förening, vilket betyder att alla beslut om
föreningens inriktning fattas gemensamt av våra medlemmar. Som medlem kan du
delta på alla möten i föreningen, inklusive styrelsens möten.

Det huvudsakliga sättet att påverka är emellertid genom föreningens
årsmöten. Det ska inte bara vara de som har tid att vara med på precis varje
möte som ska ha möjlighet att påverka föreningen.

Vi strävar hela tiden efter att förbättra föreningens genomskinlighet. Det
ska vara lätt att hitta information om föreningens verksamhet, vare sig det
gäller nästa träff, senaste mötesprotokollet eller information om våra tekniska
system.

Våra tekniska lösningar [[http://git.fripost.org/][dokumenterar]] vi utförligt och historik över förändringar
sparar vi med ett versionshanteringssystem.  Det gör det enkelt för den som vill
(och kan) att följa administratörernas arbete på nära håll.

På den här sidan hittar du mer information om föreningen. Om någonting saknas
eller är oklart, tveka inte att [[file:kontakt.org][höra av dig]] till oss med dina synpunkter.

#+HTML: <a name="meetings"><div class="divider"></div></a>
* Möten och sammanträden

Möten och aktiviteter är ständigt på gång. Medlemmar och intresserade är
hjärtligt välkomna till mötena för att se hur arbetet går till. Om det inte står
något annat brukar vi träffas på [[file:gnutiken.org][Gnutiken]].

På [[http://wiki.fripost.org/moten/][vår wiki]] finns en aktuell lista över kommande möten samt protokoll från
tidigare möten.

#+HTML: <div class="divider"></div>

* Stadgar

Föreningen antog stadgar vid årsmötet 2010 (se nedan). Du kan hitta stadgarna [[file:material/stadgar2010.pdf][här]].

 - [[file:material/stadgar2010.pdf][Fripost stadgar sedan november 2010]]

#+HTML: <a name="board"><div class="divider"></div></a>

* Styrelsen

** Styrelsens uppgifter

Enligt föreningens stadgar ska styrelsen:

- Arbeta för att ta emot medlemmarnas e-post på ett tillförlitligt sätt
- Sörja för god transparens vad gäller administration, ekonomi och styrning
- Arbeta för att skydda medlemmarnas integritet, d.v.s. att aldrig
  - Läsa eller analysera medlemmars e-posttrafik, manuellt eller automatiskt
  - Samla statistik om, eller analysera medlemmarnas e-posttrafik via
    föreningens servrar
  - Under inga omständigheter lämna ut uppgifter om medlemmar, deras
    e-posttrafik, eller andra förehavanden till tredje part
    
** Styrelsens sammansättning

#+BEGIN_HTML
<!-- TODO: lägg in folk i en tabell och visa deras e-postadresser, kanske som bild -->
<p>Stefan Kangas (ordförande)<br />
Gustav Eek<br />
Leif-Jöran Olsson<br />
Stian Rødven Eide (suppleant)<br />
Ver Takeo (suppleant)</p>
#+END_HTML

** Administrativa rättigheter

Administratörsrättigheter ges av styrelsen efter behov. För närvarande har
Stefan Kangas, Gustav Eek och Leif-Jöran Olsson administratörsrättigheter på
samtliga system.

** Styrelsemöten och mötesprotokoll

   En transparent administration och beslutsprocess är centralt för föreningen. Medlemmar och intresserade välkomnas därför att delta på styrelsens möten. Information om styrelsens sammanträden, dagordningar och protokoll underhålls på Friposts medlemswiki: [[http://wiki.fripost.org/moten][wiki.fripost.org]]. 

#+HTML: <div class="divider"></div>

* Händelser (events)

Att driva e-postkommunikation är ett av Friposts åtaganden, men inte det enda.

För att sprida information om nätfrihet och engagera fler personer annordnar vi också en rad olika aktiviteter.

** 2011-03-13 Friposts första fest

I mars kunde Fripost stolt inviga uppstarten och bjuda till fest: "Friposts första fest", eller "FFFFEFFF, Fripost, föreningen för fri e-posts, första fria fest". Platsen var [[file:gnutiken.org][Gnutiken]] Övre Husargatan 27, Göteborg (vid Linnéplatsen)

- Aktivitetsschema:

   | 14:00 | Filmvisning: /The Conversation/ (Coppola,1974)          |
   | 16:30 | Presentation av föreningen (Stefan Kangas, ordförande)  |
   | 18:00 | Workshop: "Lär dig kryptera e-post" (Stian Rødven Eide) |
   | 19:00 | Fest                                                    |

Festen var en lyckad tillställning och flera nya personer bestämde sig för att gå med i föreningen. Detta gör att Fripost lovar arrangera en ny fest. Namnforslag och förslag på teman för kommande fester: FSF, /Friposts sommarfest/; FSCONES, /Friposts  sconesfest/.

 - [[file:material/affisch-12-mars.pdf][Festens affisch]]

** 2010-12-09 Öppet möte om kryptering av e-post

Leif-Jöran berättade om kryptering och signering av e-post och alla som ville
fick byta PGP-nycklar och intygas för cacert.

** 2010-11-07 Deltagande på FSCONS

   Gustav Eek och Stefan Kangas höll en presentation om Fripost på konferensen
   [[http://fscons.org][FSCONS]]. Allt material är på engelska.

   - En [[http://fscons.org/2010/infrastructure/distributed-email-system][Sammanfattning]] 
   - Videoupptagning från föredraget
     - [[http://vimeo.com/22228099][Del 1 av 3]]
     - [[http://vimeo.com/22228273][Del 2 av 3]]
     - [[http://vimeo.com/22228306][Del 3 av 3]]
   - [[http://www.slideshare.net/fscons/2010-11-eek-kangas-5745050][Bildspel]]


#+HTML: <div class="divider"></div>

* Övrigt

Mer information kan du hitta på [[http://fellowship.se/wiki/Projekt/friepost/][Fellowship of Free Software Foundation Europe
Göteborgs wiki-sida]].  Fripost började som ett projekt inom den föreningen, men
är nu helt fristående.

Det finns [[file:material/leaflet.pdf][ett flygblad]] som togs fram till FSCONS.  Det får du gärna skriva ut
och sprida till andra.  Flygbladet är på engelska.

Vår [[http://git.fripost.org][hemsida]] och [[http://git.fripost.org][tekniska dokumentation]] finns tillgängligt i [[http://git-scm.com/][git-förråd]].

Se [[file:medlemskap.org][medlemssidan]] för mer information om hur du kan gå med i Fripost.
