#+TITLE:     Föreningen Fripost
#+SETUPFILE: includes/level-0.org

Fripost är en demokratisk förening, vilket betyder att alla beslut om
föreningens inriktning fattas gemensamt av våra medlemmar. Som medlem kan du
delta på alla möten i föreningen, inklusive styrelsens möten.

Det huvudsakliga sättet att påverka är emellertid genom föreningens
årsmöten. Det ska inte bara vara de som har tid att vara med på precis varje
möte som ska ha möjlighet att påverka föreningen. Nästa årsmöte är planerat
någon gång till våren 2011.

Vi strävar hela tiden efter att förbättra föreningens genomskinlighet. Det
ska vara lätt att hitta information om föreningens verksamhet, vare sig det
gäller nästa träff, senaste mötesprotokollet eller information om våra tekniska
system.

Våra tekniska lösningar [[https://github.com/skangas/fripost-docs][dokumenterar]] vi utförligt och historik över förändringar
sparar vi med ett versionshanteringssystem.  Det gör det enkelt för den som vill
(och kan) att följa administratörernas arbete på nära håll.

På den här sidan hittar du mer information om föreningen. Om någonting saknas
eller är oklart, tveka inte att [[file:kontakt.org][höra av dig]] till oss med dina synpunkter.

#+HTML: <div class="divider"></div>

* Stadgar

Föreningen antog stadgar vid årsmötet 2010 (se nedan). Du kan hitta stadgarna [[file:material/stadgar2010.pdf][här]]. 

#+HTML: <div class="divider"></div>

* Styrelsen

** Styrelsens uppgifter

Enligt föreningens stadgar ska styrelsen:

- Arbeta för att ta emot medlemmarnas e-post på ett tillförlitligt sätt
- Sörja för god transparens vad gäller administration, ekonomi och styrning
- Arbeta för att skydda medlemmarnas integritet, d.v.s. att aldrig
  - Läsa eller analysera medlemmars e-posttrafik, manuellt eller automatiskt
  - Samla statistik om, eller analysera medlemmarnas e-posttrafik via
    föreningens servrar
  - Under inga omständigheter lämna ut uppgifter om medlemmar, deras
    e-posttrafik, eller andra förehavanden till tredje part
    
** Styrelsens sammansättning

#+BEGIN_HTML
<!-- TODO: lägg in folk i en tabell och visa deras e-postadresser, kanske som bild -->
<p>Stefan Kangas (ordförande)<br />
Gustav Eek<br />
Leif-Jöran Olsson<br />
Stian Rødven Eide (suppleant)<br />
Ver Takeo (suppleant)</p>
#+END_HTML

** Administrativa rättigheter

Administratörsrättigheter ges av styrelsen efter behov. För närvarande har
Stefan Kangas, Gustav Eek och Leif-Jöran Olsson administratörsrättigheter på
samtliga system.

#+HTML: <div class="divider"></div>

* Mötesrapporter och protokoll

** 2011-02-20 Styrelsemöte

Mötet diskuterade åter mestadels Friposts fest 12 mars. Bl.a. budgeterades 300 kr till att trycka affischer. Festens totala budget är 730 kr, men föreningen räknar med ekonomiskt stöd och med inkomster under festen, så att den bringar pengar in i föreningens kassa. 

 - [[file:minutes/2011-02-20-board.pdf][Protokoll styrelsemöte 20 februari 2011]]


** 2011-02-13 Styrelsemöte

Mötets syfte var att diskutera Friposts fest 12 mars. Formen var informell.

 - [[file:minutes/2011-02-13-board-notes.pdf][Anteckningar styrelsemöte 13 februari 2011]]

** 2011-02-03 Styrelsemöte

På grund av sjukdom blev det inget formellt möte.  Istället gick vi igenom och
diskuterade vissa detaljer i e-postsystemet.

** 2011-01-26 Styrelsemöte

/Protokoll kommer snart.../

** 2011-01-20 Styrelsemöte

 - [[file:minutes/2011-01-20-board.pdf][Protokoll styrelsemöte 2011-01-20]]

** 2011-01-10 Styrelsemöte

Diskussioner framför allt om föreningens ekonomi och servrar. Beslut att köpa in
två stycken externa 2TB USB-hårddiskar till säkerhetskopior och att vi under
nästa vecka försöker få igång den av Leif-Jöran utlånade RAID-arrayen. Denna ska
fungera som huvudsaklig IMAP tills vidare.

 - [[file:minutes/2011-01-10-board.pdf][Protokoll styrelsemöte 2011-01-10]

** 2010-12-09 Öppet möte om kryptering av e-post

Styrelsen träffades som hastigast innan mötet för att diskutera arbetet. Fokus
ligger på att bygga upp serverinfrastrukturen just nu, ett arbete som kommer ske
under hela jullovet. Tahoe Filesystem diskuterades.

Leif-Jöran berättade om kryptering och signering av e-post och alla som ville
fick byta PGP-nycklar och intygas för cacert.

- [[file:minutes/2010-12-09-board-notes.pdf][Anteckningar styrelsemöte 2010-12-09]]

** 2010-11-17 Styrelsemöte

Diskuterades bland annat antal begränsningar för e-postadresser, alias och egna domäner.

- [[file:minutes/fripost-board-2010-11-17.pdf][Protokoll styrelsemöte 2010-11-17]]

** 2010-11-07 Deltagande på FSCONS

Gustav Eek och Stefan Kangas höll en presentation om Fripost på konferensen
[[http://fscons.org][FSCONS]]. Du kan läsa deras abstract [[http://fscons.org/infrastructure/distributed-email-system][här]] (engelska).  Deras slides hittar du [[http://www.slideshare.net/fscons/2010-11-eek-kangas-5745050][här]].

** 2010-11-04 Föreningen bildades

Vi grundade föreningen formellt efter mycket planering och förberedande.

- [[file:minutes/fripost-founding-2010-11-04.pdf][Protokoll från årsmötet 2010-11-04]]

** Tidiga arbetsmöten

- [[file:minutes/2010-10-28.txt][Anteckningar från arbetsmöte 2010-10-28]]
- [[file:minutes/2010-10-07.txt][Anteckningar från arbetsmöte 2010-10-07]]
- [[file:minutes/2010-06-21.txt][Anteckningar från arbetsmöte 2010-06-21]]

#+HTML: <div class="divider"></div>

* Övrigt

Mer information kan du hitta på [[http://fellowship.se/wiki/Projekt/friepost/][Fellowship of Free Software Foundation Europe
Göteborgs wiki-sida]].  Fripost började som ett projekt inom den föreningen, men
är nu helt fristående.

Det finns [[file:material/leaflet.pdf][ett flygblad]] som togs fram till FSCONS.  Det får du gärna skriva ut
och sprida till andra.  Flygbladet är på engelska.

Vår [[http://github.com/skangas/fripost-web][hemsida]] och [[https://github.com/skangas/fripost-docs][tekniska dokumentation]] finns tillgängligt i [[http://git-scm.com/][git-förråd]].

Se [[file:medlemskap.org][medlemssidan]] för mer information om hur du kan gå med i Fripost.
