#+TITLE:     Föreningen Fripost
#+SETUPFILE: includes/level-0.org

Fripost är en demokratisk förening, vilket betyder att alla beslut om
föreningens inriktning fattas gemensamt av våra medlemmar. Som medlem kan du
delta på alla möten i föreningen, inklusive styrelsens möten.

Det huvudsakliga sättet att påverka är emellertid genom föreningens
årsmöten. Det ska inte bara vara de som har tid att vara med på precis varje
möte som ska ha möjlighet att påverka föreningen.

Vi strävar hela tiden efter att förbättra föreningens genomskinlighet. Det
ska vara lätt att hitta information om föreningens verksamhet, vare sig det
gäller nästa träff, senaste mötesprotokollet eller information om våra tekniska
system.

Våra tekniska lösningar [[https://github.com/skangas/fripost-docs][dokumenterar]] vi utförligt och historik över förändringar
sparar vi med ett versionshanteringssystem.  Det gör det enkelt för den som vill
(och kan) att följa administratörernas arbete på nära håll.

På den här sidan hittar du mer information om föreningen. Om någonting saknas
eller är oklart, tveka inte att [[file:kontakt.org][höra av dig]] till oss med dina synpunkter.

#+HTML: <a name="meetings"><div class="divider"></div></a>
* Möten och sammanträden

Flera möten är inplanerade. Medlemmar och intresserade är hjärtligt välkomna till mötena för att se hur arbetet går till.

 - Tisdag 5 april kl 18.00, styrelsemöte. Mötet sker på Språkbanken, Lennart Torstenssons gata 7.
 - Onsdag 13 april kl 18.00, medlemsmöte. Inget årsmöte kommer hållas under 2011 (se mötet 10 mars), men Fripost bjuder in till medlemsmöte.
 - Onsdag 27 april kl 18.00, styrelsemöte. 
 - Onsdag 18 maj kl 18.00, styrelsemöte.

[[file:index.org][Till startsidan]]

#+HTML: <div class="divider"></div>

* Stadgar

Föreningen antog stadgar vid årsmötet 2010 (se nedan). Du kan hitta stadgarna [[file:material/stadgar2010.pdf][här]].

 - [[file:material/stadgar2010.pdf][Fripost stadgar sedan november 2010]]

#+HTML: <a name="board"><div class="divider"></div></a>

* Styrelsen

** Styrelsens uppgifter

Enligt föreningens stadgar ska styrelsen:

- Arbeta för att ta emot medlemmarnas e-post på ett tillförlitligt sätt
- Sörja för god transparens vad gäller administration, ekonomi och styrning
- Arbeta för att skydda medlemmarnas integritet, d.v.s. att aldrig
  - Läsa eller analysera medlemmars e-posttrafik, manuellt eller automatiskt
  - Samla statistik om, eller analysera medlemmarnas e-posttrafik via
    föreningens servrar
  - Under inga omständigheter lämna ut uppgifter om medlemmar, deras
    e-posttrafik, eller andra förehavanden till tredje part
    
** Styrelsens sammansättning

#+BEGIN_HTML
<!-- TODO: lägg in folk i en tabell och visa deras e-postadresser, kanske som bild -->
<p>Stefan Kangas (ordförande)<br />
Gustav Eek<br />
Leif-Jöran Olsson<br />
Stian Rødven Eide (suppleant)<br />
Ver Takeo (suppleant)</p>
#+END_HTML

** Administrativa rättigheter

Administratörsrättigheter ges av styrelsen efter behov. För närvarande har
Stefan Kangas, Gustav Eek och Leif-Jöran Olsson administratörsrättigheter på
samtliga system.

** Styrelsemöten och mötesprotokoll

   En transparent administration och beslutsprocess är centralt för föreningen. Medlemmar och intresserade välkomnas därför att delta på styrelsens möten. Information om styrelsens sammanträden, dagordningar och protokoll underhålls på Friposts medlemswiki: [[http://wiki.fripost.org/moten][wiki.fripost.org]]. 

#+HTML: <div class="divider"></div>

* Händelser (events)

  Att driva e-post kommunikation är ett av Fripoståtaganden, men inte det ända...

  Med syfte att sprida information om nätfrihet och engagera fler personer annordnar Fripost också flera aktiviteter. 

** 2010-12-09 Öppet möte om kryptering av e-post

Leif-Jöran berättade om kryptering och signering av e-post och alla som ville
fick byta PGP-nycklar och intygas för cacert.

** 2010-11-07 Deltagande på FSCONS

Gustav Eek och Stefan Kangas höll en presentation om Fripost på konferensen
[[http://fscons.org][FSCONS]]. Du kan läsa deras abstract [[http://fscons.org/infrastructure/distributed-email-system][här]] (engelska).  Deras slides hittar du [[http://www.slideshare.net/fscons/2010-11-eek-kangas-5745050][här]].

#+HTML: <div class="divider"></div>

* Övrigt

Mer information kan du hitta på [[http://fellowship.se/wiki/Projekt/friepost/][Fellowship of Free Software Foundation Europe
Göteborgs wiki-sida]].  Fripost började som ett projekt inom den föreningen, men
är nu helt fristående.

Det finns [[file:material/leaflet.pdf][ett flygblad]] som togs fram till FSCONS.  Det får du gärna skriva ut
och sprida till andra.  Flygbladet är på engelska.

Vår [[http://github.com/skangas/fripost-web][hemsida]] och [[https://github.com/skangas/fripost-docs][tekniska dokumentation]] finns tillgängligt i [[http://git-scm.com/][git-förråd]].

Se [[file:medlemskap.org][medlemssidan]] för mer information om hur du kan gå med i Fripost.
